### PR TITLE
Assignment 6

### PR DESCRIPTION
**Pull request by labiagajaime**

### CODE REVIEW

**Comment by rgcmme** [comment]
- You are updating 72 files from the repository in the pull request. Make a new clean pull request only with your files.

**Comment by labiagajaime** [comment]
Those files are necesary in order to no confilcts. I have been pushing my assignments like this one all the term

**Comment by rgcmme** [comment]
Try to update your local copy of the repository before submitting your changes.

**Comment by labiagajaime** [comment]
my commands:
>git fetch upstream
>git merge upstream/master
Make changes
>git commit -m "changes"
>git push

I don't see what I'm doing wrong

**Comment by rgcmme** [comment]
Try using "git status" and "git diff" to see what are the differences between the repository and your local copy.
If all the files still appear as modified, try (without deleting your data) to get a clean copy of the repository in another directory and apply your changes over that copy.

**Comment by labiagajaime** [comment]
Done. My local copy has not differences between the repository. No files modified. Everything looks fine

**Comment by rgcmme** [comment]
Perfect, the you can make a new pull request.

**Comment by labiagajaime** [comment]
Know are conflicts on the main repository. I open a issue

**Comment by labiagajaime** [comment]
Now there are no conflicts at this moment.

I restore my local copy with the repository content, added Assignment 6 and create pull request.

Thank you

**Comment by rgcmme** [comment]
Good!

**Pull request closed without merging**
