### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by scriam**
I did only the exercise 1.b, becuse I don't have a moodle account to get StickyNote_PureRDF.rdf file.

### CODE REVIEW

**Comment by nandana** [comment]
Hi, you can find the content of the StickyNote_PureRDF.rdf file in the following link. Please submit the exercise 1.a in a separate pull request.

https://gist.github.com/nandana/757413331b1510d97f15bb3740cc59e0

**Comment by nandana** [comment]
Hi, can you please add your name here as well. I can't find it from your GitHub repo. Thank you!

**Comment by scriam** [comment]
My surname and name is: Tertiuc Afanasie

**Comment by nandana** [comment]
Thanks Afanasie! Don't forget to submit the Assignment 1. I couldn't find your name in the following file.
https://github.com/FacultadInformatica-LinkedData/Curso2016-2017/blob/master/Assignment1/DatasetDescriptions.csv

**Assignment 1.** Please fill in a line with a dataset description about a single city at folder Assignment 1,  and make a pull request.

**Pull request merged**
